BEGIN TRANSACTION;
DELETE FROM banks;
INSERT INTO banks (mfo, name) VALUES (300001, '"НАЦіОНАЛЬНИЙ БАНК"');
INSERT INTO banks (mfo, name) VALUES (300002, 'АТ "Укрексімбанк"');
INSERT INTO banks (mfo, name) VALUES (300003, 'ПАТ "Промінвестбанк"');
INSERT INTO banks (mfo, name) VALUES (300004, 'ПАТ "УКРСОЦБАНК"');
INSERT INTO banks (mfo, name) VALUES (300005, 'АТ "ОЩАДБАНК"');
INSERT INTO banks (mfo, name) VALUES (300006, 'ПАТ "ЛЕГБАНК"');
INSERT INTO banks (mfo, name) VALUES (300007, 'ПАТ "УКРіНБАНК"');
INSERT INTO banks (mfo, name) VALUES (300008, 'ПУАТ "ФіДОБАНК"');
INSERT INTO banks (mfo, name) VALUES (300009, 'ПАТ "інтеграл-банк"');
INSERT INTO banks (mfo, name) VALUES (300010, 'ПАТ "ЕНЕРГОБАНК"');
INSERT INTO banks (mfo, name) VALUES (300011, 'ПАТ КБ "іНТЕРБАНК"');
INSERT INTO banks (mfo, name) VALUES (300012, 'АТ "Райффайзен Банк Аваль"');
INSERT INTO banks (mfo, name) VALUES (300013, 'АТ "БРОКБіЗНЕСБАНК"');
INSERT INTO banks (mfo, name) VALUES (300014, 'ПАТ "ВТБ БАНК"');
INSERT INTO banks (mfo, name) VALUES (300015, 'ПАТ "НЕОС БАНК"');
INSERT INTO banks (mfo, name) VALUES (300016, 'ПАТ КБ "ПРИВАТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300017, 'АКБ "НОВИЙ"');
INSERT INTO banks (mfo, name) VALUES (300018, 'ПОЛіКОМБАНК');
INSERT INTO banks (mfo, name) VALUES (300019, 'ПАТ "ПРОФіН БАНК"');
INSERT INTO banks (mfo, name) VALUES (300020, 'ПАТ "АКБ "КАПіТАЛ"');
INSERT INTO banks (mfo, name) VALUES (300021, 'АТ "РОДОВіД БАНК"');
INSERT INTO banks (mfo, name) VALUES (300022, 'АТ "КБ "ЕКСПОБАНК"');
INSERT INTO banks (mfo, name) VALUES (300023, 'ПУБЛіЧНЕ АТ"БАНК ФАМіЛЬНИЙ"');
INSERT INTO banks (mfo, name) VALUES (300024, 'ПАТ "ВіЕйБі Банк"');
INSERT INTO banks (mfo, name) VALUES (300025, 'АТ "БАНК "ТАВРИКА"');
INSERT INTO banks (mfo, name) VALUES (300026, 'ПАТ АКБ "ЛЬВіВ"');
INSERT INTO banks (mfo, name) VALUES (300027, 'ПАТ "ОКСі БАНК"');
INSERT INTO banks (mfo, name) VALUES (300028, 'ПАТ "А - БАНК"');
INSERT INTO banks (mfo, name) VALUES (300029, 'ПАТ "ВіЕс Банк"');
INSERT INTO banks (mfo, name) VALUES (300030, 'АТ БАНК"МЕРКУРіЙ"У М.ХАРКіВ');
INSERT INTO banks (mfo, name) VALUES (300031, 'Акціонерний банк"Південний"');
INSERT INTO banks (mfo, name) VALUES (300032, 'АБ "ПОРТО-ФРАНКО"');
INSERT INTO banks (mfo, name) VALUES (300033, 'ПАТ "КБ "іНВЕСТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300034, 'ПАТ "Полтава-банк"');
INSERT INTO banks (mfo, name) VALUES (300035, 'ПАT "ПУМБ"');
INSERT INTO banks (mfo, name) VALUES (300036, 'ПАТ "ФіНБАНК"');
INSERT INTO banks (mfo, name) VALUES (300037, 'ПАТ "БАНК "ГРАНТ"');
INSERT INTO banks (mfo, name) VALUES (300038, 'АТ "РЕГіОН-БАНК"');
INSERT INTO banks (mfo, name) VALUES (300039, 'АТ "УКРСИББАНК"');
INSERT INTO banks (mfo, name) VALUES (300040, 'ПАТ "КОМіНВЕСТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300041, 'ПАТКБ "ПРАВЕКС-БАНК"');
INSERT INTO banks (mfo, name) VALUES (300042, 'АТ "ФіНРОСТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300043, 'АТ "НК БАНК"');
INSERT INTO banks (mfo, name) VALUES (300044, 'ПАТ АКБ "АРКАДА"');
INSERT INTO banks (mfo, name) VALUES (300045, 'ПАТ "АКБ Банк"');
INSERT INTO banks (mfo, name) VALUES (300046, 'ПАТ Банк "Контракт"');
INSERT INTO banks (mfo, name) VALUES (300047, 'АТ "МетаБанк"');
INSERT INTO banks (mfo, name) VALUES (300048, 'АТ "БАНК ЗОЛОТі ВОРОТА"');
INSERT INTO banks (mfo, name) VALUES (300049, 'АБ "УКООПСПіЛКА"');
INSERT INTO banks (mfo, name) VALUES (300050, 'ПАТ "КБ "Надра"');
INSERT INTO banks (mfo, name) VALUES (300051, 'Філ."КіБ" "КРЕДі АГРіКОЛЬ"');
INSERT INTO banks (mfo, name) VALUES (300052, 'ПАТ "КСГ БАНК"');
INSERT INTO banks (mfo, name) VALUES (300053, 'ПАТ "КБ "ЗЕМЕЛЬНИЙ КАПіТАЛ"');
INSERT INTO banks (mfo, name) VALUES (300054, 'АТ "іМЕКСБАНК"');
INSERT INTO banks (mfo, name) VALUES (300055, 'АБ "ЕКСПРЕС-БАНК"');
INSERT INTO banks (mfo, name) VALUES (300056, 'АТ "СП БАНК"');
INSERT INTO banks (mfo, name) VALUES (300057, '"БАНК НАЦіОНАЛЬНИЙ КРЕДИТ"');
INSERT INTO banks (mfo, name) VALUES (300058, 'ПАТ "УКРГАЗПРОМБАНК"');
INSERT INTO banks (mfo, name) VALUES (300059, 'ПАТ "ТЕРРА БАНК"');
INSERT INTO banks (mfo, name) VALUES (300060, 'АБ "КЛіРИНГОВИЙ ДіМ"');
INSERT INTO banks (mfo, name) VALUES (300061, '"ПЕРШИЙ іНВЕСТИЦіЙНИЙ БАНК"');
INSERT INTO banks (mfo, name) VALUES (300062, 'ПАТ "ПФБ" м.Кременчук');
INSERT INTO banks (mfo, name) VALUES (300063, 'ПАТ "іНГ Банк Укра∙на"');
INSERT INTO banks (mfo, name) VALUES (300064, 'АТ "ОТП Банк"');
INSERT INTO banks (mfo, name) VALUES (300065, 'ПАТ "СіТіБАНК"');
INSERT INTO banks (mfo, name) VALUES (300066, 'АТ "ПРОКРЕДИТ БАНК"');
INSERT INTO banks (mfo, name) VALUES (300067, 'АТ "СБЕРБАНК РОСі°"');
INSERT INTO banks (mfo, name) VALUES (300068, 'ПАТ "ПРАЙМ-БАНК"');
INSERT INTO banks (mfo, name) VALUES (300069, 'ПАТ "КБ "АКТИВ - БАНК"');
INSERT INTO banks (mfo, name) VALUES (300070, 'АТ "АРТЕМ-БАНК"');
INSERT INTO banks (mfo, name) VALUES (300071, 'АТ "ФОРТУНА-БАНК"');
INSERT INTO banks (mfo, name) VALUES (300072, 'ПАТ "БАНК ВОСТОК"');
INSERT INTO banks (mfo, name) VALUES (300073, 'ПАТ "УНіКОМБАНК"');
INSERT INTO banks (mfo, name) VALUES (300074, 'АТ "БАНК РЕНЕСАНС КАПіТАЛ"');
INSERT INTO banks (mfo, name) VALUES (300075, 'ПАТ "ФіНЕКСБАНК"');
INSERT INTO banks (mfo, name) VALUES (300076, 'ДЕРЖКАЗНСЛУЖБА УКРА°НИ,КИ°В');
INSERT INTO banks (mfo, name) VALUES (300077, 'ПрАТ "УФГ"');
INSERT INTO banks (mfo, name) VALUES (300078, 'ПАТ "ОМЕГА БАНК"');
INSERT INTO banks (mfo, name) VALUES (300079, 'АТ"БАНК"ФіНАНСИ ТА КРЕДИТ"');
INSERT INTO banks (mfo, name) VALUES (300080, 'ПАТ "БАНК АЛЬЯНС"');
INSERT INTO banks (mfo, name) VALUES (300081, 'ПАТ "УПБ"');
INSERT INTO banks (mfo, name) VALUES (300082, 'ПАТ "КБ "ПіВДЕНКОМБАНК"');
INSERT INTO banks (mfo, name) VALUES (300083, 'ПАТ "ЮСБ БАНК"');
INSERT INTO banks (mfo, name) VALUES (300084, 'ПАТ "КБ "ПРОМЕКОНОМБАНК"');
INSERT INTO banks (mfo, name) VALUES (300085, 'АТ "ТАСКОМБАНК"');
INSERT INTO banks (mfo, name) VALUES (300086, 'ПАТ "СТАРОКИ°ВСЬКИЙ БАНК"');
INSERT INTO banks (mfo, name) VALUES (300087, 'ПАТ "КРЕДОБАНК"');
INSERT INTO banks (mfo, name) VALUES (300088, 'АКБ "іНДУСТРіАЛБАНК"');
INSERT INTO banks (mfo, name) VALUES (300089, 'ПАТ "МАРФіН БАНК"');
INSERT INTO banks (mfo, name) VALUES (300090, 'ПАТ "РЕАЛ БАНК"');
INSERT INTO banks (mfo, name) VALUES (300091, 'ПАТ "МЕГАБАНК", Харків');
INSERT INTO banks (mfo, name) VALUES (300092, 'ПАТ "ГРіН БАНК"');
INSERT INTO banks (mfo, name) VALUES (300093, 'ПАТ "БТА Банк"');
INSERT INTO banks (mfo, name) VALUES (300094, 'ПАТ "АСВіО БАНК"');
INSERT INTO banks (mfo, name) VALUES (300095, 'Банк "Демарк"');
INSERT INTO banks (mfo, name) VALUES (300096, 'ПАТ "ідея Банк"');
INSERT INTO banks (mfo, name) VALUES (300097, 'ПАТ"БАНК "УКРА°Н.КАПіТАЛ"');
INSERT INTO banks (mfo, name) VALUES (300098, 'ПАТ "ФіНАНС БАНК"');
INSERT INTO banks (mfo, name) VALUES (300099, 'ПАТ "КРЕДі АГРіКОЛЬ БАНК"');
INSERT INTO banks (mfo, name) VALUES (300100, 'ПАТ "УКРБіЗНЕСБАНК"');
INSERT INTO banks (mfo, name) VALUES (300101, 'ПАТ "УКРКОМУНБАНК"');
INSERT INTO banks (mfo, name) VALUES (300102, 'ПАТ "КБ "ХРЕЩАТИК"');
INSERT INTO banks (mfo, name) VALUES (300103, 'ПАТ "АКБ "КИ°В"');
INSERT INTO banks (mfo, name) VALUES (300104, 'АТ "МіСТО БАНК"');
INSERT INTO banks (mfo, name) VALUES (300105, 'ПАТ АБ "СТОЛИЧНИЙ"');
INSERT INTO banks (mfo, name) VALUES (300106, 'БАНК НАЦіОНАЛЬНі іНВЕСТИЦі°');
INSERT INTO banks (mfo, name) VALUES (300107, 'ПАТ "БГ БАНК"');
INSERT INTO banks (mfo, name) VALUES (300108, 'ПАТ "ЮНЕКС БАНК" м. Ки∙в');
INSERT INTO banks (mfo, name) VALUES (300109, 'ПАТ "ДіАМАНТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300110, 'АТ "КіБ"');
INSERT INTO banks (mfo, name) VALUES (300111, 'ПАТ "АГРОКОМБАНК"');
INSERT INTO banks (mfo, name) VALUES (300112, 'ПАТ "УНіВЕРСАЛ БАНК"');
INSERT INTO banks (mfo, name) VALUES (300113, 'ПАТ "БАНК ФОРУМ"');
INSERT INTO banks (mfo, name) VALUES (300114, 'АТ "ПіРЕУС БАНК МКБ"');
INSERT INTO banks (mfo, name) VALUES (300115, 'АТ "БАНК ВЕЛЕС"');
INSERT INTO banks (mfo, name) VALUES (300116, 'АТ КБ "ТК КРЕДИТ"');
INSERT INTO banks (mfo, name) VALUES (300117, 'ПАТ "БАНК КРЕДИТ ДНіПРО"');
INSERT INTO banks (mfo, name) VALUES (300118, 'ПАТ "АЛЬФА-БАНК"');
INSERT INTO banks (mfo, name) VALUES (300119, 'ПАТ "Західінкомбанк"');
INSERT INTO banks (mfo, name) VALUES (300120, 'АБ "УКРГАЗБАНК"');
INSERT INTO banks (mfo, name) VALUES (300121, 'ПАТ "КЛАСИКБАНК"');
INSERT INTO banks (mfo, name) VALUES (300122, 'ПАТ "БАНК "КИ°ВСЬКА РУСЬ"');
INSERT INTO banks (mfo, name) VALUES (300123, '"БАНК ПЕТРОКОММЕРЦ-УКРА°НА"');
INSERT INTO banks (mfo, name) VALUES (300124, 'ПАТ "АБ "РАДАБАНК"');
INSERT INTO banks (mfo, name) VALUES (300125, 'ПАТ "КРЕДИТПРОМБАНК"');
INSERT INTO banks (mfo, name) VALUES (300126, 'Центральне сховище НБУ');
INSERT INTO banks (mfo, name) VALUES (300127, 'Упр. НБУ у Вінницькій обл.');
INSERT INTO banks (mfo, name) VALUES (300128, 'Упр. НБУ у Волинській обл.');
INSERT INTO banks (mfo, name) VALUES (300129, 'Упр. НБУ в Луганській обл.');
INSERT INTO banks (mfo, name) VALUES (300130, 'Упр. НБУ в Дніпропетр.обл.');
INSERT INTO banks (mfo, name) VALUES (300131, 'Упр. НБУ в Житомир. обл.');
INSERT INTO banks (mfo, name) VALUES (300132, 'Упр. НБУ в Закарпат.обл');
INSERT INTO banks (mfo, name) VALUES (300133, 'Упр. НБУ в Запорізькій обл.');
INSERT INTO banks (mfo, name) VALUES (300134, 'Упр. НБУ у  Хмельницьк.обл.');
INSERT INTO banks (mfo, name) VALUES (300135, 'ГУ НБУ по м.Київу і області');
INSERT INTO banks (mfo, name) VALUES (300136, 'Упр. НБУ в Кіровоград. обл.');
INSERT INTO banks (mfo, name) VALUES (300137, 'ГУ НБУ в  АРК');
INSERT INTO banks (mfo, name) VALUES (300138, 'Упр. НБУ у Львівській обл.');
INSERT INTO banks (mfo, name) VALUES (300139, 'Упр. НБУ в Микола∙в. обл.');
INSERT INTO banks (mfo, name) VALUES (300140, 'Упр. НБУ в Одеській обл.');
INSERT INTO banks (mfo, name) VALUES (300141, 'Упр. НБУ в Полтавській обл.');
INSERT INTO banks (mfo, name) VALUES (300142, 'Упр. НБУ в Рівненській обл.');
INSERT INTO banks (mfo, name) VALUES (300143, 'Упр. НБУ в Донецькій обл.');
INSERT INTO banks (mfo, name) VALUES (300144, 'Упр. НБУ ів-Фpанків. обл.');
INSERT INTO banks (mfo, name) VALUES (300145, 'Упр. НБУ в Сумській обл.');
INSERT INTO banks (mfo, name) VALUES (300146, 'Упр. НБУ в Тернопіл. обл.');
INSERT INTO banks (mfo, name) VALUES (300147, 'Упр. НБУ в Харківській обл.');
INSERT INTO banks (mfo, name) VALUES (300148, 'Упр. НБУ в Херсонській обл.');
INSERT INTO banks (mfo, name) VALUES (300149, 'Упр.НБУ в Чернігівській обл');
INSERT INTO banks (mfo, name) VALUES (300150, 'Упр. НБУ в Чеpкаській обл.');
INSERT INTO banks (mfo, name) VALUES (300151, 'Упр. НБУ в Чернівецькій обл');
INSERT INTO banks (mfo, name) VALUES (300152, 'Державна скарбниця');
INSERT INTO banks (mfo, name) VALUES (300153, 'Центральна РП НБУ');
INSERT INTO banks (mfo, name) VALUES (300154, 'Банкнотно-монетний двір');
INSERT INTO banks (mfo, name) VALUES (300155, 'Фабрика банкнотного паперу');
INSERT INTO banks (mfo, name) VALUES (300156, 'Львів.інстит.БС УБС(м.Ки∙в)');
INSERT INTO banks (mfo, name) VALUES (300157, 'Харків.ін-т банк.справи УБС');
INSERT INTO banks (mfo, name) VALUES (300158, 'Черк.інстит.банк.справи УБС');
INSERT INTO banks (mfo, name) VALUES (300159, 'ДВНЗ "УКР.АКАДЕМіЯ БС НБУ"');
INSERT INTO banks (mfo, name) VALUES (300160, 'Центральний апарат НБУ');
INSERT INTO banks (mfo, name) VALUES (300161, 'ГУП НБУ');
INSERT INTO banks (mfo, name) VALUES (300162, 'ГГУ НБУ');
INSERT INTO banks (mfo, name) VALUES (300163, 'Ф-я Укрексімбанк, Вінниця');
INSERT INTO banks (mfo, name) VALUES (300164, 'Ф-я Укрексімбанк, Луцьк');
INSERT INTO banks (mfo, name) VALUES (300165, 'Ф-я Укрексімбанк, Луганськ');
INSERT INTO banks (mfo, name) VALUES (300166, 'Ф-я Укрексiмбанк,Кривий Ріг');
INSERT INTO banks (mfo, name) VALUES (300167, 'Ф.Укрексiмбанк,м.Дніпропетр');
INSERT INTO banks (mfo, name) VALUES (300168, 'Ф-я Укрексімбанк, Житомир');
INSERT INTO banks (mfo, name) VALUES (300169, 'Ф-я Укрексімбанк,Ужгород');
INSERT INTO banks (mfo, name) VALUES (300170, 'Ф-я Укрексімбанк,Запоріжжя');
INSERT INTO banks (mfo, name) VALUES (300171, 'Ф-я"Укрексімбанк",Хмельн.');
INSERT INTO banks (mfo, name) VALUES (300172, 'Ф-я Укрексімбанк, Кіровогр');
INSERT INTO banks (mfo, name) VALUES (300173, 'Ф-я.Укрексімбанк,Львів');
INSERT INTO banks (mfo, name) VALUES (300174, 'Ф-я Укрексімбанк, Микола∙в');
INSERT INTO banks (mfo, name) VALUES (300175, 'Ф-я Укрексімбанк, Одеса');
INSERT INTO banks (mfo, name) VALUES (300176, 'Ф-я Укрексімбанк, ізма∙л');
INSERT INTO banks (mfo, name) VALUES (300177, 'Ф-я Укрексімбанк, Полтава');
INSERT INTO banks (mfo, name) VALUES (300178, 'Ф-я Укрексімбанк, Рівне');
INSERT INTO banks (mfo, name) VALUES (300179, 'Ф-я Укрексiмбанк, м.Донецьк');
INSERT INTO banks (mfo, name) VALUES (300180, 'Ф-я Укрексiмбанк, Маріуполь');
INSERT INTO banks (mfo, name) VALUES (300181, 'Ф.Укрексімбанк, ів.-Франк');
INSERT INTO banks (mfo, name) VALUES (300182, 'Ф-я Укрексімбанк,Тернопіль');
INSERT INTO banks (mfo, name) VALUES (300183, 'Ф-я "Укрексімбанк", Харків');
INSERT INTO banks (mfo, name) VALUES (300184, 'Ф-я "Укрексімбанк", Херсон');
INSERT INTO banks (mfo, name) VALUES (300185, 'Ф-я "Укрексімбанк",Чернігів');
INSERT INTO banks (mfo, name) VALUES (300186, 'Ф-я "Укрексімбанк", Черкаси');
INSERT INTO banks (mfo, name) VALUES (300187, 'Ф-я Укрексімбанк,Чернівці');
INSERT INTO banks (mfo, name) VALUES (300188, 'Ф-я Укрексімбанк, Ки∙в');
INSERT INTO banks (mfo, name) VALUES (300189, 'ФВінницьке обласне уАТОщад');
INSERT INTO banks (mfo, name) VALUES (300190, 'ФВолинське обласне уАТОщад');
INSERT INTO banks (mfo, name) VALUES (300191, 'ФЛуганське обласне уАТОщад');
INSERT INTO banks (mfo, name) VALUES (300192, 'ФДніпропетровське обАТОщад');
INSERT INTO banks (mfo, name) VALUES (300193, 'ФЖитомирське обласнеАТОщад');
INSERT INTO banks (mfo, name) VALUES (300194, 'ФЗакарпатське обласнАТОщад');
INSERT INTO banks (mfo, name) VALUES (300195, 'ФЗапорізьке обласне АТОщад');
INSERT INTO banks (mfo, name) VALUES (300196, 'ФХмельницьке обласнеАТОщад');
INSERT INTO banks (mfo, name) VALUES (300197, 'ФКіровоградське ОУ АТОщад');
INSERT INTO banks (mfo, name) VALUES (300198, 'ФКримське  республікАТОщад');
INSERT INTO banks (mfo, name) VALUES (300199, 'ФЛьвівське обласне уАТОщад');
INSERT INTO banks (mfo, name) VALUES (300200, 'ФМикола∙вське обласнАТОщад');
INSERT INTO banks (mfo, name) VALUES (300201, 'ФОдеське обласне упрАТОщад');
INSERT INTO banks (mfo, name) VALUES (300202, 'ФПолтавське обласне АТОщад');
INSERT INTO banks (mfo, name) VALUES (300203, 'ФРівненське обласне АТОщад');
INSERT INTO banks (mfo, name) VALUES (300204, 'ФДонецьке обласне упАТОщад');
INSERT INTO banks (mfo, name) VALUES (300205, 'Фівано-ФранківськеОУАТОщадб');
INSERT INTO banks (mfo, name) VALUES (300206, 'ФСумське обласне упрАТОщад');
INSERT INTO banks (mfo, name) VALUES (300207, 'ФТернопільське обласАТОщад');
INSERT INTO banks (mfo, name) VALUES (300208, 'ФХарківське обласне АТОщад');
INSERT INTO banks (mfo, name) VALUES (300209, 'ФХерсонське ОУ АТОщад');
INSERT INTO banks (mfo, name) VALUES (300210, 'ФЧернігівське обласнАТОщад');
INSERT INTO banks (mfo, name) VALUES (300211, 'ФЧеркаське ОУ АТОщадбанк');
INSERT INTO banks (mfo, name) VALUES (300212, 'ФЧернівецьке обласнеАТОщад');
INSERT INTO banks (mfo, name) VALUES (300213, 'Ф "ЦРУ" АТ"Б" ФіН ТА КРЕД"');
INSERT INTO banks (mfo, name) VALUES (300214, 'КрфАТ"Б"ФіНАНСИ ТА КРЕДИТ"');
INSERT INTO banks (mfo, name) VALUES (300215, 'Ф"ЗРУ"АТ"Б"Фін. та Кред"');
INSERT INTO banks (mfo, name) VALUES (300216, 'Ф ОРУ АТ"Б"ФіНАНСИ ТА КРЕД');
INSERT INTO banks (mfo, name) VALUES (300217, 'ВінницькаОДАТ"Райф.Б.Аваль"');
INSERT INTO banks (mfo, name) VALUES (300218, 'ВолинськаОДАТ"Райф.Б.Аваль"');
INSERT INTO banks (mfo, name) VALUES (300219, 'Дніпр-ськаОДАТ"Райф.Б.Аваль');
INSERT INTO banks (mfo, name) VALUES (300220, 'Житомир.ОДАТ"Райф.Б.Аваль"');
INSERT INTO banks (mfo, name) VALUES (300221, 'Закарпат.ОДАТ"Райф.Б.Аваль"');
INSERT INTO banks (mfo, name) VALUES (300222, 'Запоріж.ОДАТ"Райф.Б.Аваль"');
INSERT INTO banks (mfo, name) VALUES (300223, 'Хмельниц.ОДАТ"Райф.Б.Аваль"');
INSERT INTO banks (mfo, name) VALUES (300224, 'Кіровогр.ОДАТ"Райф.Б.Аваль"');
INSERT INTO banks (mfo, name) VALUES (300225, 'ЛьвівськаОДАТ"Райф.Б.Аваль"');
INSERT INTO banks (mfo, name) VALUES (300226, 'Микола∙в.ОДАТ"Райф.Б.Аваль"');
INSERT INTO banks (mfo, name) VALUES (300227, 'ОдеськаОД АТ "Райф.Б.Аваль"');
INSERT INTO banks (mfo, name) VALUES (300228, 'Полтав.ОДАТ"Райф.Б.Аваль"');
INSERT INTO banks (mfo, name) VALUES (300229, 'Рівнен.ОДАТ"Райф.Б.Аваль"');
INSERT INTO banks (mfo, name) VALUES (300230, 'ДонецькаОДАТ"Райф.Б.Аваль"');
INSERT INTO banks (mfo, name) VALUES (300231, 'ів-Франк.ОДАТ"Райф.Б.Аваль"');
INSERT INTO banks (mfo, name) VALUES (300232, 'СумськаОД АТ"Райф.Б.Аваль"');
INSERT INTO banks (mfo, name) VALUES (300233, 'Тернопіл.ОДАТ"Райф.Б.Аваль"');
INSERT INTO banks (mfo, name) VALUES (300234, 'Харків.ОД АТ"Райф.Б.Аваль"');
INSERT INTO banks (mfo, name) VALUES (300235, 'Херсон.ОД АТ"Райф.Б.Аваль"');
INSERT INTO banks (mfo, name) VALUES (300236, 'ЧД "РАЙФФАЙЗЕН БАНК АВАЛЬ"');
INSERT INTO banks (mfo, name) VALUES (300237, 'ЧеркаськаОДАТ"Райф.Б.Аваль"');
INSERT INTO banks (mfo, name) VALUES (300238, 'Чернівец.ОДАТ"Райф.Б.Аваль"');
INSERT INTO banks (mfo, name) VALUES (300239, 'АТ "Райффайзен Банк Аваль"');
INSERT INTO banks (mfo, name) VALUES (300240, 'ПЕЧЕРСЬКАФ.ПАТКБ"ПРИВАТБАНК');
INSERT INTO banks (mfo, name) VALUES (300241, 'ВіННИЦЬКА Ф.ПАТКБПРИВАТБАНК');
INSERT INTO banks (mfo, name) VALUES (300242, 'ЛУГАН.Ф-Я ПАТ КБ"ПРИВАТБАНК');
INSERT INTO banks (mfo, name) VALUES (300243, 'КРИВОРіЗЬКА Ф.ПАТКБ"ПРИВАТБ');
INSERT INTO banks (mfo, name) VALUES (300244, 'ЖИТОМ.РУ ПАТ КБ"ПРИВАТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300245, 'ЗАКАР.РУ ПАТ КБ"ПРИВАТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300246, 'ЗАП. РУ ПАТ КБ"ПРИВАТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300247, 'ХМЕЛЬН.Ф.ПАТКБ "ПРИВАТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300248, 'Ф"РОЗР.ЦЕНТР"ПАТ КБ ПРИВАТБ');
INSERT INTO banks (mfo, name) VALUES (300249, 'КИ°ВСЬКЕ ГРУ "ПРИВАТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300250, 'КіРОВ.РУ ПАТ КБ"ПРИВАТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300251, 'СЕВАС.Ф.ПАТ КБ"ПРИВАТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300252, 'ЗАХіД.ГРУПАТКБ"ПРИВАТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300253, 'МИКОЛ.РУ ПАТ КБ"ПРИВАТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300254, 'ПОЛТ.ГРУ ПАТ КБ"ПРИВАТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300255, 'РіВНЕНСЬКА Ф.ПАТКБПРИВАТБАН');
INSERT INTO banks (mfo, name) VALUES (300256, 'МАРіУП.Ф.ПАТ КБ"ПРИВАТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300257, 'ДОНЕЦЬКЕ РУ ПАТКБПРИВАТБАНК');
INSERT INTO banks (mfo, name) VALUES (300258, 'КРАМАТ.Ф.ПАТ КБ"ПРИВАТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300259, 'і-ФРАН.Ф.ПАТ КБ"ПРИВАТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300260, 'СУМСЬКА Ф.ПАТКБ"ПРИВАТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300261, 'ТЕРН.Ф.ПАТКБ ПРИВАТБАНК');
INSERT INTO banks (mfo, name) VALUES (300262, 'ХЕРСОНСЬКА Ф.ПАТ КБ ПРИВАТБ');
INSERT INTO banks (mfo, name) VALUES (300263, 'ЧЕРНіГ.РУ ПАТКБ"ПРИВАТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300264, 'ЧЕРКАСЬКЕ ГРУ "ПРИВАТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300265, 'ЧЕРНіВ.Ф.ПАТ КБ"ПРИВАТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300266, 'КФ ПАТ "КБ "ПРОМЕКОНОМБАНК"');
INSERT INTO banks (mfo, name) VALUES (300267, 'ФПАТ "КБ "іНВЕСТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300268, 'СХіДНА ДИРЕКЦЯ "МіСТО БАНК"');
INSERT INTO banks (mfo, name) VALUES (300269, 'ДОНЕЦЬКА Ф АТ "МіСТО БАНК');
INSERT INTO banks (mfo, name) VALUES (300270, 'Кі°ВСЬКА Ф АТ "МіСТО БАНК"');
INSERT INTO banks (mfo, name) VALUES (300271, 'Філія АТ"іМЕКСБАНК"ум.Київі');
INSERT INTO banks (mfo, name) VALUES (300272, 'Кримська філія АБ "Експр-Б"');
INSERT INTO banks (mfo, name) VALUES (300273, 'ГУ ДКСУ У ВіННИЦЬКіЙ ОБЛАСТ');
INSERT INTO banks (mfo, name) VALUES (300274, 'ГУ ДКСУ У ВОЛИНСЬКіЙ ОБЛАСТ');
INSERT INTO banks (mfo, name) VALUES (300275, 'ГУ ДКСУ У ЛУГАНСЬКіЙ ОБЛАСТ');
INSERT INTO banks (mfo, name) VALUES (300276, 'ГУ ДКСУ У ЖИТОМИРСЬКіЙ ОБЛА');
INSERT INTO banks (mfo, name) VALUES (300277, 'ГУ ДКСУ У ЗАКАРПАТСЬКіЙ ОБЛ');
INSERT INTO banks (mfo, name) VALUES (300278, 'ГУ ДКСУ У ЗАПОРіЗЬКіЙ ОБЛАС');
INSERT INTO banks (mfo, name) VALUES (300279, 'ГУ ДКСУ У ХМЕЛЬНИЦЬКіЙ ОБЛА');
INSERT INTO banks (mfo, name) VALUES (300280, 'ГУ ДКСУ У М.КИЇВі');
INSERT INTO banks (mfo, name) VALUES (300281, 'ГУ ДКСУ У КИ°ВСЬКіЙ ОБЛАСТі');
INSERT INTO banks (mfo, name) VALUES (300282, 'ГУ ДКСУ У КіРОВОГРАДСЬКіЙ О');
INSERT INTO banks (mfo, name) VALUES (300283, 'ГУ ДКСУ В АРК, М.СіМФЕРОПОЛ');
INSERT INTO banks (mfo, name) VALUES (300284, 'ГУ ДКСУ У М.СЕВАСТОПОЛі');
INSERT INTO banks (mfo, name) VALUES (300285, 'ГУ ДКСУ У ЛЬВіВСЬКіЙ ОБЛАСТ');
INSERT INTO banks (mfo, name) VALUES (300286, 'ГУ ДКСУ У МИКОЛА°ВСЬКіЙ ОБЛ');
INSERT INTO banks (mfo, name) VALUES (300287, 'ГУ ДКСУ В ОДЕСЬКіЙ ОБЛАСТі');
INSERT INTO banks (mfo, name) VALUES (300288, 'ГУ ДКСУ У ПОЛТАВСЬКіЙ ОБЛАС');
INSERT INTO banks (mfo, name) VALUES (300289, 'ГУ ДКСУ У РіВНЕНСЬКіЙ ОБЛАС');
INSERT INTO banks (mfo, name) VALUES (300290, 'ГУ ДКСУ У ДОНЕЦЬКіЙ ОБЛАСТі');
INSERT INTO banks (mfo, name) VALUES (300291, 'ГУ ДКСУ В іВАНО-ФРАНКіВСЬКі');
INSERT INTO banks (mfo, name) VALUES (300292, 'ГУ ДКСУ У СУМСЬКіЙ ОБЛАСТі');
INSERT INTO banks (mfo, name) VALUES (300293, 'ГУ ДКСУ У ТЕРНОПіЛЬСЬКіЙ ОБ');
INSERT INTO banks (mfo, name) VALUES (300294, 'ГУ ДКСУ У ХАРКіВСЬКіЙ ОБЛАС');
INSERT INTO banks (mfo, name) VALUES (300295, 'ГУ ДКСУ У ХЕРСОНСЬКіЙ ОБЛАС');
INSERT INTO banks (mfo, name) VALUES (300296, 'ГУ ДКСУ У ЧЕРНіГіВСЬКіЙ ОБЛ');
INSERT INTO banks (mfo, name) VALUES (300297, 'ГУ ДКСУ У ЧЕРКАСЬКіЙ ОБЛАСТ');
INSERT INTO banks (mfo, name) VALUES (300298, 'ГУ ДКСУ У ЧЕРНіВЕЦЬКіЙ ОБЛА');
INSERT INTO banks (mfo, name) VALUES (300299, 'Перша ФПрАТ "УФГ",м.Вінниця');
INSERT INTO banks (mfo, name) VALUES (300300, 'Ф ПрАТ "УФГ" у м.Кривий Ріг');
INSERT INTO banks (mfo, name) VALUES (300301, 'Дн-ська обласна ФПрАТ "УФГ"');
INSERT INTO banks (mfo, name) VALUES (300302, 'Закарпат. обл. ФПрАТ "УФГ"');
INSERT INTO banks (mfo, name) VALUES (300303, 'Хмельницька обл. Ф ПрАТ УФГ');
INSERT INTO banks (mfo, name) VALUES (300304, 'Ф ПрАТ "УФГ" у м.Кіровоград');
INSERT INTO banks (mfo, name) VALUES (300305, 'Ф ПрАТ "УФГ" у м.Микола∙в');
INSERT INTO banks (mfo, name) VALUES (300306, 'Одеська обл. філія ПрАТ УФГ');
INSERT INTO banks (mfo, name) VALUES (300307, 'Філія ПрАТ "УФГ" у м.Одеса');
INSERT INTO banks (mfo, name) VALUES (300308, 'Друга ФПрАТ УФГ у м.Полтава');
INSERT INTO banks (mfo, name) VALUES (300309, 'Філія ПрАТ УФГ м.Кременчук');
INSERT INTO banks (mfo, name) VALUES (300310, 'Перша ФПрАТ УФГ м.Кременчук');
INSERT INTO banks (mfo, name) VALUES (300311, 'Філія ПрАТ УФГ у м.Донецьк');
INSERT INTO banks (mfo, name) VALUES (300312, 'івано-Франк. рег. ФПрАТ УФГ');
INSERT INTO banks (mfo, name) VALUES (300313, 'ФПрАТ УФГ у м.івано-Франк.');
INSERT INTO banks (mfo, name) VALUES (300314, 'Перша ФПрАТ УФГ м.івано-Фр.');
INSERT INTO banks (mfo, name) VALUES (300315, 'Філія ПрАТ "УФГ" у м.Харків');
INSERT INTO banks (mfo, name) VALUES (300316, 'Філія ПрАТ "УФГ" у м.Херсон');
INSERT INTO banks (mfo, name) VALUES (300317, 'Філія ПрАТ УФГ у м.Черкаси');
INSERT INTO banks (mfo, name) VALUES (300318, 'Чернівецька обласна ФАТ"УФГ');
INSERT INTO banks (mfo, name) VALUES (300319, 'Перша ФПрАТ УФГ м.Кіровогр.');
INSERT INTO banks (mfo, name) VALUES (300320, 'ФПрАТ УФГ у м.Світловодськ');
INSERT INTO banks (mfo, name) VALUES (300321, 'Кіровоград. обл. ФПрАТ УФГ');
INSERT INTO banks (mfo, name) VALUES (300322, 'Друга Севастоп. ФПрАТ "УФГ"');
INSERT INTO banks (mfo, name) VALUES (300323, 'Кримська філія ПрАТ "УФГ"');
INSERT INTO banks (mfo, name) VALUES (300324, 'Перша ФПрАТ УФГ у м.Львів');
INSERT INTO banks (mfo, name) VALUES (300325, 'Друга ФПрАТ УФГ у м.Львів');
INSERT INTO banks (mfo, name) VALUES (300326, 'Філія ПрАТ УФГ у м.Дрогобич');
INSERT INTO banks (mfo, name) VALUES (300327, 'Перша ФПрАТ УФГ у м.Микол.');
INSERT INTO banks (mfo, name) VALUES (300328, 'Тернопільска філія ПрАТ УФГ');
INSERT INTO banks (mfo, name) VALUES (300329, 'Перша ФПрАТ УФГ м.Тернопіль');
INSERT INTO banks (mfo, name) VALUES (300330, 'ФГоловне управління АТОщад');
INSERT INTO banks (mfo, name) VALUES (300331, 'Ки∙вська РДАТ"Райф.Б.Аваль"');
INSERT INTO banks (mfo, name) VALUES (300332, 'ВОЛ.ГРУ ПАТ КБ "ПРИВАТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300333, 'ЮЖНЕ ГРУ ПАТ КБ"ПРИВАТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300334, 'ХАРК.ГРУ ПАТ КБ"ПРИВАТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300335, 'КРИМ.РУ ПАТ КБ "ПРИВАТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300336, 'Луган.філіяПАТ"АКБ"КАПіТАЛ"');
INSERT INTO banks (mfo, name) VALUES (300337, 'ГУ ДКСУ У ДНіПРОПЕТРОВСЬКіЙ');
INSERT INTO banks (mfo, name) VALUES (300338, 'ПАТ "КБ "УФС"');
INSERT INTO banks (mfo, name) VALUES (300339, 'Запорізька обл. ФПрАТ УФГ');
INSERT INTO banks (mfo, name) VALUES (300340, 'Перша ФПрАТ УФГ у м.Харків');
INSERT INTO banks (mfo, name) VALUES (300341, 'ПАТ "КБ "ДАНіЕЛЬ"');
INSERT INTO banks (mfo, name) VALUES (300342, 'Ф"ДРРУ"АТ Банк"Фін та Кред"');
INSERT INTO banks (mfo, name) VALUES (300343, 'Ф"ПРУ"АТ"Б" Фін. та Кред."');
INSERT INTO banks (mfo, name) VALUES (300344, 'Ки∙вська ф-я ПАТ "МЕГАБАНК"');
INSERT INTO banks (mfo, name) VALUES (300345, 'ПАТ "АКБ "Траст-капітал"');
INSERT INTO banks (mfo, name) VALUES (300346, 'Укр.банк реконстр.та розв.');
INSERT INTO banks (mfo, name) VALUES (300347, 'Ф.ПРУБАНК ФіНАНСИ ТА КРЕДИТ');
INSERT INTO banks (mfo, name) VALUES (300348, 'АТ "УКРБУДіНВЕСТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300349, 'ПАТ "БАНК КАМБіО"');
INSERT INTO banks (mfo, name) VALUES (300350, 'ПАТ "ПтБ"');
INSERT INTO banks (mfo, name) VALUES (300351, 'ПАТ КБ"ФіНАНСОВА іНіЦіАТИВА');
INSERT INTO banks (mfo, name) VALUES (300352, 'ПАТ КБ "ЇВРОБАНК"');
INSERT INTO banks (mfo, name) VALUES (300353, 'Ки∙в.Філія ПАТ"АКБ"КАПіТАЛ"');
INSERT INTO banks (mfo, name) VALUES (300354, 'ФПрАТ УФГ у м.Червоноград');
INSERT INTO banks (mfo, name) VALUES (300355, 'ДНіПР.Ф АТ "МіСТО БАНК"');
INSERT INTO banks (mfo, name) VALUES (300356, 'ФАТ "іМЕКСБАНК" у м. Одеса');
INSERT INTO banks (mfo, name) VALUES (300357, 'БАНК іНВЕСТ. ТА ЗАОЩАДЖЕНЬ');
INSERT INTO banks (mfo, name) VALUES (300358, 'Ф"КИ°ВСіТі"ПАТ КБ"ПРИВАТБ"');
INSERT INTO banks (mfo, name) VALUES (300359, 'АТ "БМ БАНК"');
INSERT INTO banks (mfo, name) VALUES (300360, 'ПАТ "КБ "АКСіОМА"');
INSERT INTO banks (mfo, name) VALUES (300361, 'АТ "Дельта Банк"');
INSERT INTO banks (mfo, name) VALUES (300362, 'ПАТ "БАНК ФОРВАРД"');
INSERT INTO banks (mfo, name) VALUES (300363, 'ПАТ "МіСЬКИЙ КОМЕРЦ. БАНК"');
INSERT INTO banks (mfo, name) VALUES (300364, 'СТОЛИЧНА Ф ПАТ КБ "ПРИВАТБ"');
INSERT INTO banks (mfo, name) VALUES (300365, 'ПАТ "АКБ "КОНКОРД"');
INSERT INTO banks (mfo, name) VALUES (300366, 'АТ "БАНК БОГУСЛАВ"');
INSERT INTO banks (mfo, name) VALUES (300367, 'Перша КФПАТ "інтеграл-банк"');
INSERT INTO banks (mfo, name) VALUES (300368, 'ПАТ "КРЕДИТ ЇВРОПА БАНК"');
INSERT INTO banks (mfo, name) VALUES (300369, 'АТ "ЇВРОГАЗБАНК"');
INSERT INTO banks (mfo, name) VALUES (300370, 'ПАТ "КРЕДИТВЕСТ БАНК"');
INSERT INTO banks (mfo, name) VALUES (300371, 'АТ "ЕРДЕ БАНК"');
INSERT INTO banks (mfo, name) VALUES (300372, 'ПАТ "КРЕДИТ ОПТИМА БАНК"');
INSERT INTO banks (mfo, name) VALUES (300373, 'Ауд.Ф"ПрайсвотерхаусКуперс"');
INSERT INTO banks (mfo, name) VALUES (300374, 'Ф"МРУ" АТ"КБ"Експобанк"');
INSERT INTO banks (mfo, name) VALUES (300375, 'Ф АТ"Укрексімбанк" СУМИ');
INSERT INTO banks (mfo, name) VALUES (300376, 'ПАТ "КБ "ПРЕМіУМ"');
INSERT INTO banks (mfo, name) VALUES (300377, 'ПАТ БАНК "ТРАСТ"');
INSERT INTO banks (mfo, name) VALUES (300378, 'ПАТ "МОТОР-БАНК"');
INSERT INTO banks (mfo, name) VALUES (300379, 'ЛВФ ПАТ "Банк"Ки∙вськаРусь"');
INSERT INTO banks (mfo, name) VALUES (300380, 'АТ "КБ "СОЮЗ"');
INSERT INTO banks (mfo, name) VALUES (300381, 'ПАТ "КБ "ГЛОБУС"');
INSERT INTO banks (mfo, name) VALUES (300382, 'УНіВЕРСИТЕТ БС НБУ м.КИ°В');
INSERT INTO banks (mfo, name) VALUES (300383, 'ПАТ "АСТРА БАНК"');
INSERT INTO banks (mfo, name) VALUES (300384, 'УДППЗ "Укрпошта"');
INSERT INTO banks (mfo, name) VALUES (300385, 'ПАТ "МіБ"');
INSERT INTO banks (mfo, name) VALUES (300386, 'Ф"Одес.РУ" АТ"КБ"Експобанк"');
INSERT INTO banks (mfo, name) VALUES (300387, 'ПАТ "АКТАБАНК"');
INSERT INTO banks (mfo, name) VALUES (300388, 'АТ "ЗЛАТОБАНК"');
INSERT INTO banks (mfo, name) VALUES (300389, 'ПуАТ "КБ "АКОРДБАНК"');
INSERT INTO banks (mfo, name) VALUES (300390, 'ПАТ "БАНК 3/4"');
INSERT INTO banks (mfo, name) VALUES (300391, 'Одеська філія ПрАТ "УФГ"');
INSERT INTO banks (mfo, name) VALUES (300392, 'ПАТ "ЇВРОПРОМБАНК"');
INSERT INTO banks (mfo, name) VALUES (300393, 'Ки∙вська філія ПАТ"ПФБ"');
INSERT INTO banks (mfo, name) VALUES (300394, 'Перша ФПрАТ УФГ м.Луганськ');
INSERT INTO banks (mfo, name) VALUES (300395, 'ПАТ КБ "СТАНДАРТ"');
INSERT INTO banks (mfo, name) VALUES (300396, 'ПАТ "ВЕРНУМ БАНК"');
INSERT INTO banks (mfo, name) VALUES (300397, 'ПАТ "АВАНТ-БАНК"');
INSERT INTO banks (mfo, name) VALUES (300398, 'Регіон. ФПрАТ УФГ м.Харків');
INSERT INTO banks (mfo, name) VALUES (300399, 'Волинська філія ПрАТ "УФГ"');
INSERT INTO banks (mfo, name) VALUES (300400, 'ПАТ "ВБР"');
INSERT INTO banks (mfo, name) VALUES (300401, 'ЦФ ПрАТ "УФГ" у м. Харків');
INSERT INTO banks (mfo, name) VALUES (300402, 'Філія ПрАТ УФГ у м.Луганськ');
INSERT INTO banks (mfo, name) VALUES (300403, 'ПАТ "АПЕКС-БАНК"');
INSERT INTO banks (mfo, name) VALUES (300404, 'ПАТ "Дойче Банк ДБУ"');
INSERT INTO banks (mfo, name) VALUES (300405, 'Черкаська філія ПрАТ "УФГ"');
INSERT INTO banks (mfo, name) VALUES (300406, 'Закарп. рег. ФПрАТ "УФГ"');
INSERT INTO banks (mfo, name) VALUES (300407, 'ПАТ "РАДИКАЛ БАНК"');
INSERT INTO banks (mfo, name) VALUES (300408, 'ПАТ "РОЗРАХУНКОВИЙ ЦЕНТР"');
INSERT INTO banks (mfo, name) VALUES (300409, 'ПАТ КБ "Центр"');
INSERT INTO banks (mfo, name) VALUES (300410, 'ЦФ ПАТ "МАРФіН БАНК"');
INSERT INTO banks (mfo, name) VALUES (300411, 'СіБС УБС НБУ');
INSERT INTO banks (mfo, name) VALUES (300412, 'ПУАТ "СМАРТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300413, 'Чорн Ф ПАТ"Б."Ки∙вськаРусь"');
INSERT INTO banks (mfo, name) VALUES (300414, 'Харків. обл. філія ПрАТ УФГ');
INSERT INTO banks (mfo, name) VALUES (300415, 'Одеська рег. філія ПрАТ УФГ');
INSERT INTO banks (mfo, name) VALUES (300416, 'ЦФ ПрАТ "УФГ" у м. Чернівці');
INSERT INTO banks (mfo, name) VALUES (300417, 'ПАТ"СЕБ КОРПОРАТИВНИЙ БАНК"');
INSERT INTO banks (mfo, name) VALUES (300418, 'ПАТ "БАНК СіЧ"');
INSERT INTO banks (mfo, name) VALUES (300419, 'ПАТ "ДіВі БАНК"');
INSERT INTO banks (mfo, name) VALUES (300420, 'ПАТ "іНТЕРКРЕДИТБАНК"');
INSERT INTO banks (mfo, name) VALUES (300421, 'ТОВ "ФК "Вікторія"');
INSERT INTO banks (mfo, name) VALUES (300422, 'ТОВ Фінансова установа ГГЛА');
INSERT INTO banks (mfo, name) VALUES (300423, 'ТОВ "ФіН.КОМ. АБСОЛЮТ ФіН."');
INSERT INTO banks (mfo, name) VALUES (300424, 'ПАТ "МЕЛіОР БАНК"');
INSERT INTO banks (mfo, name) VALUES (300425, 'ПАТ "БАНК "СОФіЙСЬКИЙ"');
INSERT INTO banks (mfo, name) VALUES (300426, 'Харківська філія ПрАТ "УФГ"');
INSERT INTO banks (mfo, name) VALUES (300427, 'ПАТ "КБ"ФіНАНСОВИЙ ПАРТНЕР"');
INSERT INTO banks (mfo, name) VALUES (300428, 'ПАТ "АЛЬПАРі БАНК"');
INSERT INTO banks (mfo, name) VALUES (300429, '5-та філія у м.Одеса');
INSERT INTO banks (mfo, name) VALUES (300430, 'ПАТ "БАНК "ЮНіСОН"');
INSERT INTO banks (mfo, name) VALUES (300431, 'ТОВ"ФК АБСОЛЮТ ФіНАНС ГРУП"');
INSERT INTO banks (mfo, name) VALUES (300432, 'ПАТ "БАНК МИХАЙЛіВСЬКИЙ"');
INSERT INTO banks (mfo, name) VALUES (300433, 'ПАТ "БАНК АВАНГАРД"');
INSERT INTO banks (mfo, name) VALUES (300434, 'ТОВ "БТБ"');
INSERT INTO banks (mfo, name) VALUES (300435, 'ПАТ"іНВЕСТИЦіЙНО-ТРАСТ.БАНК');
INSERT INTO banks (mfo, name) VALUES (300436, 'ПАТ "Держзембанк"');
INSERT INTO banks (mfo, name) VALUES (300437, 'ПАТ "БАНК "ПОРТАЛ"');
INSERT INTO banks (mfo, name) VALUES (300438, 'ПАТ "КБ "ГЕФЕСТ"');
INSERT INTO banks (mfo, name) VALUES (300439, 'ТОВ "ФіНОД"');
INSERT INTO banks (mfo, name) VALUES (300440, 'ПАТ "ВЕКТОР БАНК"');
INSERT INTO banks (mfo, name) VALUES (300441, 'ФіЛіЯ "КД" ПАТ "УНіКОМБАНК"');
INSERT INTO banks (mfo, name) VALUES (300442, 'Казначейство Укра∙ни (еап)');
INSERT INTO banks (mfo, name) VALUES (300443, 'ПАТ"ПЕРЕХ.БАНК"КРИСТАЛБАНК"');
ENd TRANSACTION;