ALTER TABLE pin_codes
ADD "whenIssuedPassport" DATE NOT NULL,
ADD "issuedPassport" CHARACTER VARYING NOT NULL,
ADD "passportNumber" CHARACTER VARYING NOT NULL,
ADD "firstName" CHARACTER VARYING NOT NULL,
ADD "lastName" CHARACTER VARYING NOT NULL,
ADD "patronymic" CHARACTER VARYING NOT NULL,
ADD "isDeleted" BOOLEAN NOT NULL DEFAULT FALSE;