ALTER TABLE personal_accounts
ADD COLUMN "lastName" CHARACTER VARYING NOT NULL DEFAULT 'NULL',
ADD COLUMN "firstName" CHARACTER VARYING NOT NULL DEFAULT 'NULL',
ADD COLUMN "patronymic" CHARACTER VARYING NOT NULL DEFAULT 'NULL';